builds:
- env:
  - CGO_ENABLED=0
  binary: pick-a-browser
  goos:
    - windows
  goarch:
    - 386
    - amd64
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -H windowsgui

archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip


changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
